TAROT_CARDS = [
    # 메이저 아르카나 (0-21)
    {"id": 0,  "name": "The Fool",          "name_kr": "바보",          "keywords": "새로운 시작, 자유, 모험, 순수함"},
    {"id": 1,  "name": "The Magician",      "name_kr": "마법사",        "keywords": "의지, 창조, 능력, 집중"},
    {"id": 2,  "name": "The High Priestess","name_kr": "여사제",        "keywords": "직관, 신비, 내면의 지혜, 잠재력"},
    {"id": 3,  "name": "The Empress",       "name_kr": "여황제",        "keywords": "풍요, 모성, 자연, 창조성"},
    {"id": 4,  "name": "The Emperor",       "name_kr": "황제",          "keywords": "권위, 안정, 리더십, 구조"},
    {"id": 5,  "name": "The Hierophant",    "name_kr": "교황",          "keywords": "전통, 가르침, 신념, 규범"},
    {"id": 6,  "name": "The Lovers",        "name_kr": "연인",          "keywords": "사랑, 선택, 조화, 관계"},
    {"id": 7,  "name": "The Chariot",       "name_kr": "전차",          "keywords": "승리, 의지력, 통제, 전진"},
    {"id": 8,  "name": "Strength",          "name_kr": "힘",            "keywords": "용기, 인내, 내면의 힘, 온화함"},
    {"id": 9,  "name": "The Hermit",        "name_kr": "은둔자",        "keywords": "성찰, 고독, 지혜, 내면 탐구"},
    {"id": 10, "name": "Wheel of Fortune",  "name_kr": "운명의 수레바퀴","keywords": "변화, 운명, 순환, 전환점"},
    {"id": 11, "name": "Justice",           "name_kr": "정의",          "keywords": "공정, 진실, 균형, 결과"},
    {"id": 12, "name": "The Hanged Man",    "name_kr": "매달린 남자",   "keywords": "희생, 기다림, 새로운 시각, 내려놓음"},
    {"id": 13, "name": "Death",             "name_kr": "죽음",          "keywords": "변환, 끝과 시작, 변화, 전환"},
    {"id": 14, "name": "Temperance",        "name_kr": "절제",          "keywords": "균형, 조화, 인내, 통합"},
    {"id": 15, "name": "The Devil",         "name_kr": "악마",          "keywords": "집착, 욕망, 속박, 물질주의"},
    {"id": 16, "name": "The Tower",         "name_kr": "탑",            "keywords": "갑작스런 변화, 충격, 해방, 깨달음"},
    {"id": 17, "name": "The Star",          "name_kr": "별",            "keywords": "희망, 치유, 영감, 신뢰"},
    {"id": 18, "name": "The Moon",          "name_kr": "달",            "keywords": "환상, 불안, 무의식, 혼돈"},
    {"id": 19, "name": "The Sun",           "name_kr": "태양",          "keywords": "기쁨, 성공, 활력, 명확함"},
    {"id": 20, "name": "Judgement",         "name_kr": "심판",          "keywords": "각성, 재생, 결단, 새출발"},
    {"id": 21, "name": "The World",         "name_kr": "세계",          "keywords": "완성, 성취, 통합, 여행"},

    # 완드 (Wands) - 22~35
    {"id": 22, "name": "Ace of Wands",      "name_kr": "완드 에이스",   "keywords": "새로운 시작, 열정, 영감, 창조"},
    {"id": 23, "name": "Two of Wands",      "name_kr": "완드 2",        "keywords": "계획, 비전, 결정, 미래"},
    {"id": 24, "name": "Three of Wands",    "name_kr": "완드 3",        "keywords": "확장, 탐험, 기다림, 선견지명"},
    {"id": 25, "name": "Four of Wands",     "name_kr": "완드 4",        "keywords": "축하, 안정, 공동체, 기쁨"},
    {"id": 26, "name": "Five of Wands",     "name_kr": "완드 5",        "keywords": "경쟁, 갈등, 도전, 에너지"},
    {"id": 27, "name": "Six of Wands",      "name_kr": "완드 6",        "keywords": "승리, 인정, 자신감, 성공"},
    {"id": 28, "name": "Seven of Wands",    "name_kr": "완드 7",        "keywords": "방어, 도전, 용기, 입장"},
    {"id": 29, "name": "Eight of Wands",    "name_kr": "완드 8",        "keywords": "속도, 행동, 소식, 움직임"},
    {"id": 30, "name": "Nine of Wands",     "name_kr": "완드 9",        "keywords": "인내, 회복력, 경계, 피로"},
    {"id": 31, "name": "Ten of Wands",      "name_kr": "완드 10",       "keywords": "부담, 책임, 완고함, 완성"},
    {"id": 32, "name": "Page of Wands",     "name_kr": "완드 시종",     "keywords": "탐험, 호기심, 자유, 열정"},
    {"id": 33, "name": "Knight of Wands",   "name_kr": "완드 기사",     "keywords": "모험, 충동, 행동, 에너지"},
    {"id": 34, "name": "Queen of Wands",    "name_kr": "완드 여왕",     "keywords": "자신감, 카리스마, 독립, 결단"},
    {"id": 35, "name": "King of Wands",     "name_kr": "완드 왕",       "keywords": "리더십, 비전, 기업가, 영감"},

    # 컵 (Cups) - 36~49
    {"id": 36, "name": "Ace of Cups",       "name_kr": "컵 에이스",     "keywords": "새로운 감정, 직관, 사랑, 창의성"},
    {"id": 37, "name": "Two of Cups",       "name_kr": "컵 2",          "keywords": "파트너십, 연결, 상호 매력, 조화"},
    {"id": 38, "name": "Three of Cups",     "name_kr": "컵 3",          "keywords": "우정, 축하, 모임, 기쁨"},
    {"id": 39, "name": "Four of Cups",      "name_kr": "컵 4",          "keywords": "명상, 무관심, 재평가, 성찰"},
    {"id": 40, "name": "Five of Cups",      "name_kr": "컵 5",          "keywords": "후회, 슬픔, 상실, 실망"},
    {"id": 41, "name": "Six of Cups",       "name_kr": "컵 6",          "keywords": "향수, 순수함, 어린 시절, 추억"},
    {"id": 42, "name": "Seven of Cups",     "name_kr": "컵 7",          "keywords": "환상, 선택, 공상, 환영"},
    {"id": 43, "name": "Eight of Cups",     "name_kr": "컵 8",          "keywords": "이별, 추구, 포기, 여행"},
    {"id": 44, "name": "Nine of Cups",      "name_kr": "컵 9",          "keywords": "만족, 행복, 소원성취, 풍요"},
    {"id": 45, "name": "Ten of Cups",       "name_kr": "컵 10",         "keywords": "행복한 가정, 조화, 완성, 기쁨"},
    {"id": 46, "name": "Page of Cups",      "name_kr": "컵 시종",       "keywords": "창의성, 직관, 감수성, 꿈"},
    {"id": 47, "name": "Knight of Cups",    "name_kr": "컵 기사",       "keywords": "낭만, 이상주의, 감성, 제안"},
    {"id": 48, "name": "Queen of Cups",     "name_kr": "컵 여왕",       "keywords": "공감, 돌봄, 직관, 감성"},
    {"id": 49, "name": "King of Cups",      "name_kr": "컵 왕",         "keywords": "감정 조절, 지혜, 외교, 균형"},

    # 소드 (Swords) - 50~63
    {"id": 50, "name": "Ace of Swords",     "name_kr": "소드 에이스",   "keywords": "명확함, 진실, 갑작스런 변화, 돌파"},
    {"id": 51, "name": "Two of Swords",     "name_kr": "소드 2",        "keywords": "결정 장애, 균형, 갈등, 교착"},
    {"id": 52, "name": "Three of Swords",   "name_kr": "소드 3",        "keywords": "슬픔, 이별, 상처, 배신"},
    {"id": 53, "name": "Four of Swords",    "name_kr": "소드 4",        "keywords": "휴식, 회복, 성찰, 준비"},
    {"id": 54, "name": "Five of Swords",    "name_kr": "소드 5",        "keywords": "갈등, 패배, 손실, 자존심"},
    {"id": 55, "name": "Six of Swords",     "name_kr": "소드 6",        "keywords": "전환, 회복, 여행, 변화"},
    {"id": 56, "name": "Seven of Swords",   "name_kr": "소드 7",        "keywords": "속임수, 전략, 고독, 회피"},
    {"id": 57, "name": "Eight of Swords",   "name_kr": "소드 8",        "keywords": "속박, 제한, 두려움, 혼란"},
    {"id": 58, "name": "Nine of Swords",    "name_kr": "소드 9",        "keywords": "불안, 걱정, 공포, 악몽"},
    {"id": 59, "name": "Ten of Swords",     "name_kr": "소드 10",       "keywords": "끝, 배신, 고통, 새로운 시작"},
    {"id": 60, "name": "Page of Swords",    "name_kr": "소드 시종",     "keywords": "호기심, 경계심, 소통, 아이디어"},
    {"id": 61, "name": "Knight of Swords",  "name_kr": "소드 기사",     "keywords": "행동, 야망, 충동, 직접성"},
    {"id": 62, "name": "Queen of Swords",   "name_kr": "소드 여왕",     "keywords": "명철함, 독립, 직접적, 분별력"},
    {"id": 63, "name": "King of Swords",    "name_kr": "소드 왕",       "keywords": "권위, 지성, 진실, 명확함"},

    # 펜타클 (Pentacles) - 64~77
    {"id": 64, "name": "Ace of Pentacles",  "name_kr": "펜타클 에이스", "keywords": "새로운 기회, 번영, 현실, 안정"},
    {"id": 65, "name": "Two of Pentacles",  "name_kr": "펜타클 2",      "keywords": "균형, 적응, 시간 관리, 우선순위"},
    {"id": 66, "name": "Three of Pentacles","name_kr": "펜타클 3",      "keywords": "협력, 기술, 성장, 팀워크"},
    {"id": 67, "name": "Four of Pentacles", "name_kr": "펜타클 4",      "keywords": "안정, 보존, 절약, 안전"},
    {"id": 68, "name": "Five of Pentacles", "name_kr": "펜타클 5",      "keywords": "어려움, 결핍, 소외, 손실"},
    {"id": 69, "name": "Six of Pentacles",  "name_kr": "펜타클 6",      "keywords": "관대함, 나눔, 균형, 지원"},
    {"id": 70, "name": "Seven of Pentacles","name_kr": "펜타클 7",      "keywords": "인내, 투자, 평가, 성장"},
    {"id": 71, "name": "Eight of Pentacles","name_kr": "펜타클 8",      "keywords": "기술, 노력, 헌신, 장인정신"},
    {"id": 72, "name": "Nine of Pentacles", "name_kr": "펜타클 9",      "keywords": "풍요, 독립, 자급자족, 성공"},
    {"id": 73, "name": "Ten of Pentacles",  "name_kr": "펜타클 10",     "keywords": "유산, 안정, 가족, 완성"},
    {"id": 74, "name": "Page of Pentacles", "name_kr": "펜타클 시종",   "keywords": "야망, 학습, 기회, 새로운 목표"},
    {"id": 75, "name": "Knight of Pentacles","name_kr": "펜타클 기사",  "keywords": "근면, 책임, 꾸준함, 신뢰"},
    {"id": 76, "name": "Queen of Pentacles","name_kr": "펜타클 여왕",   "keywords": "실용적, 모성, 풍요, 안정"},
    {"id": 77, "name": "King of Pentacles", "name_kr": "펜타클 왕",     "keywords": "부, 안정, 리더십, 현실적"},
]
